# Tyler Chat Configuration for W&B Inference (DeepSeek with Thinking Tokens)
# 
# Setup:
# 1. Get your W&B API key from: https://wandb.ai/authorize
# 2. Add to your .env file:
#    WANDB_API_KEY=<your-wandb-api-key>
#    WANDB_PROJECT=tyler-wandb  (optional - enables Weave tracing)
# 
# Note: This config uses environment variable substitution (${WANDB_API_KEY})
# Reference: https://docs.wandb.ai/guides/inference/examples/

# Agent Identity
name: "Tyler"
purpose: "To be a helpful AI assistant with access to various tools and capabilities."
notes: |
  - Prefer clear, concise communication
  - Use tools when appropriate to enhance responses
  - Maintain context across conversations

# Model Configuration - Using W&B Inference DeepSeek model
# DeepSeek models support reasoning content (thinking tokens)
# Note: The openai/ prefix tells litellm to use OpenAI-compatible format for W&B Inference
model_name: "openai/deepseek-ai/DeepSeek-R1-0528"  # Options: DeepSeek-R1-0528, DeepSeek-V3-0324, DeepSeek-V3.1

# W&B Inference endpoint configuration
# This is the standard W&B Inference API endpoint (not team/project specific)
base_url: "https://api.inference.wandb.ai/v1"

# API Key: Reads WANDB_API_KEY from environment. Set this in your .env file:
# WANDB_API_KEY=<your-api-key-from-https://wandb.ai/authorize>
api_key: "${WANDB_API_KEY}"

# Optional: Track usage by team/project
# Replace wandb/slide with your team/project if needed
extra_headers:
  HTTP-Referer: "https://wandb.ai/wandb/slide"
  X-Project-Name: "wandb-designers/slide"

temperature: 0.7
max_tool_iterations: 10

# Reasoning/Thinking Configuration
# DeepSeek models support thinking tokens when this is enabled
reasoning: "low"  # Options: "low", "medium", "high" or dict for advanced config

# Tool Configuration
tools:
  - "web"
  - "slack"
  - "notion"
  - "command_line"

# MCP (Model Context Protocol) Server Configuration
# Connect to external documentation, APIs, databases via MCP servers
# Example: Slide documentation via Mintlify MCP
# mcp:
#   servers:
#     - name: slide_docs
#       transport: sse
#       url: https://slide.mintlify.app/mcp
#       # Tools will be available as: slide_docs_search, slide_docs_query, etc.

