# Tyler Chat Configuration
# Save this file as tyler-chat-config.yaml in:
#   - Current directory
#   - ~/.tyler/chat-config.yaml
#   - /etc/tyler/chat-config.yaml
# Or specify location with: tyler-chat --config path/to/config.yaml

# Agent Identity
name: "Tyler"
purpose: "To be a helpful AI assistant with access to various tools and capabilities."
notes: |
  - Prefer clear, concise communication
  - Use tools when appropriate to enhance responses
  - Maintain context across conversations

# Model Configuration
model_name: "o3-mini"
temperature: 0.7
max_tool_iterations: 10

# Reasoning/Thinking Configuration (for models that support it)
# Enables thinking tokens to be displayed in the CLI
reasoning: "low"  # Options: "low", "medium", "high" or dict for advanced config

# Tool Configuration
# List of tools to load. Can be:
#   - Built-in tool module names (e.g., "web", "slack")
#   - Paths to Python files containing custom tools:
#     - "./my_tools.py"          # Relative to config file
#     - "~/tools/translate.py"    # User's home directory
#     - "/opt/tools/search.py"    # Absolute path
tools:
  - "web"           # Web search and browsing capabilities
  - "slack"         # Slack integration tools
  - "notion"        # Notion integration tools
  - "command_line"  # System command execution tools
  # - "./my_tools.py"  # Example custom tools (uncomment to use)

# MCP (Model Context Protocol) Server Configuration
# Connect to external documentation, APIs, databases via MCP servers
# Uncomment to enable:
# mcp:
#   servers:
#     # Example: Mintlify documentation server
#     - name: docs
#       transport: sse              # Transport: sse, websocket, or stdio
#       url: https://docs.example.com/mcp
#       # Optional: Custom headers for authentication
#       # headers:
#       #   Authorization: "Bearer ${MCP_TOKEN}"  # Use env vars for secrets
#       # Optional: Filter tools
#       # include_tools: ["search", "query"]
#       # exclude_tools: ["delete"]
#       # Optional: Custom namespace prefix (default: server name)
#       # prefix: "docs"
#       # Optional: Fail silently if server unavailable (default: true)
#       # fail_silent: true
