# Workspace configuration only - no buildable package at root
[tool.uv.workspace]
members = [
    "packages/narrator",
    "packages/tyler",
    "packages/space-monkey",
    "packages/lye",
]

# Workspace dependencies for development
[tool.uv.sources]
slide-narrator = { workspace = true }
slide-tyler = { workspace = true }
slide-space-monkey = { workspace = true }
slide-lye = { workspace = true }

# Development dependencies for the workspace
[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "pytest-cov>=6.0.0",
    "pytest-timeout>=2.1.0",
    "pytest-mock>=3.10.0",
    "python-dotenv>=1.0.0",
    "coverage>=7.6.10",
    "pip-tools>=7.4.1",
]

# Shared configuration for all packages
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short --strict-markers"
asyncio_mode = "auto"
markers = [
    "examples: Integration tests that run example files",
    "smoke: Quick smoke tests",
    "integration: Integration tests", 
    "slow: Tests that take a long time to run",
    "requires_api_key: Tests that require API keys",
    "requires_external: Tests that require external services",
]
timeout = 300