# Tyler Chat Configuration for DeepSeek Direct API (with Thinking Tokens)
# Requires: DEEPSEEK_API_KEY environment variable
# See: https://docs.litellm.ai/docs/reasoning_content

# Agent Identity
name: "Tyler"
purpose: "To be a helpful AI assistant with access to various tools and capabilities."
notes: |
  - Prefer clear, concise communication
  - Use tools when appropriate to enhance responses
  - Maintain context across conversations

# Model Configuration - Using DeepSeek directly via LiteLLM
model_name: "deepseek/deepseek-chat"
temperature: 0.7
max_tool_iterations: 10

# Reasoning/Thinking Configuration
# DeepSeek supports thinking tokens when reasoning_effort is set
reasoning_effort: "low"  # Options: low, medium, high

# Tool Configuration
tools:
  - "web"
  - "slack"
  - "notion"
  - "command_line"

