# Tyler Chat Configuration for Testing Thinking Tokens
# Use this config to test thinking tokens with Anthropic Claude

# Agent Identity
name: "Tyler"
purpose: "To be a helpful AI assistant with access to various tools and capabilities."
notes: |
  - Prefer clear, concise communication
  - Use tools when appropriate to enhance responses
  - Maintain context across conversations

# Model Configuration - Using Anthropic for thinking tokens
model_name: "anthropic/claude-3-7-sonnet-20250219"
temperature: 0.7
max_tool_iterations: 10

# Reasoning/Thinking Configuration (for models that support it)
# Enables thinking tokens to be displayed in the CLI
reasoning_effort: "low"  # Options: low, medium, high

# Tool Configuration
tools:
  - "web"
  - "slack"
  - "notion"
  - "command_line"

