[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "slide-space-monkey"
version = "0.1.0"
description = "Agent orchestration and workflow management for the Slide AI framework"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "adamwdraper"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "pydantic>=2.10.4",
    "click>=8.1.8",
    "python-dotenv>=1.0.1",
    "slide-tyler>=1.0.0",
    "slide-narrator>=0.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "pytest-cov>=6.0.0",
    "coverage>=7.6.10",
]

[project.urls]
Homepage = "https://github.com/adamwdraper/slide"
Repository = "https://github.com/adamwdraper/slide"
"Bug Tracker" = "https://github.com/adamwdraper/slide/issues"

[project.scripts]
space-monkey = "space_monkey.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["space_monkey"]

[tool.hatch.build]
include = [
    "space_monkey/**/*.py",
]
exclude = [
    "**/.env",
    "**/*.pyc",
    "**/__pycache__",
    "**/*.db",
    "**/*.sqlite",
    "**/data",
    "**/.coverage",
    "**/htmlcov",
    "**/dist",
    "**/build",
    "**/*.egg-info",
]

# Workspace dependencies for development
[tool.uv.sources]
slide-tyler = { workspace = true }
slide-narrator = { workspace = true }
