name: Unified Release

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**/pyproject.toml'
      - 'packages/**/__init__.py'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-release:
    # Only run if this is a merge from a release/v* branch
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.check.outputs.is_release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - id: check
        run: |
          # Check if this is a merge commit from a release branch
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          
          # Merge commits have format: "Merge pull request #XX from org/release/vX.Y.Z"
          if [[ "$COMMIT_MSG" =~ Merge\ pull\ request.*from.*release/v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "✓ Detected release merge for version $VERSION"
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
            echo "✗ Not a release merge, skipping"
          fi
  
  publish-all:
    needs: check-release
    if: needs.check-release.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set version from check-release job
        id: version
        run: |
          VERSION="${{ needs.check-release.outputs.version }}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install hatch
        run: uv tool install hatch
      
      - name: Create git tags
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          for PACKAGE in tyler narrator space-monkey lye; do
            TAG="$PACKAGE-v$VERSION"
            echo "Creating tag: $TAG"
            git tag -a "$TAG" -m "Release $PACKAGE version $VERSION"
            git push origin "$TAG"
          done
          
          echo "✓ All tags created and pushed"
      
      - name: Build all packages
        run: |
          for PACKAGE in tyler narrator space-monkey lye; do
            echo "::group::Building $PACKAGE"
            cd "packages/$PACKAGE"
            uv tool run hatch build
            cd ../..
            echo "::endgroup::"
            echo "::notice::$PACKAGE built successfully"
          done
      
      - name: Publish all packages to PyPI
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          for PACKAGE in tyler narrator space-monkey lye; do
            echo "::group::Publishing $PACKAGE"
            cd "packages/$PACKAGE"
            uv tool run hatch publish
            cd ../..
            echo "::endgroup::"
            echo "::notice::$PACKAGE published successfully to PyPI"
          done
      
      - name: Create GitHub releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          
          # Tyler release
          gh release create "tyler-v$VERSION" \
            --title "Tyler v$VERSION" \
            --notes "Release Tyler v$VERSION

**Package**: slide-tyler  
**Version**: $VERSION

This is part of the unified Slide release v$VERSION. All Slide packages at version $VERSION are guaranteed compatible.

See [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/packages/tyler/CHANGELOG.md) for details." \
            packages/tyler/dist/*
          
          # Narrator release
          gh release create "narrator-v$VERSION" \
            --title "Narrator v$VERSION" \
            --notes "Release Narrator v$VERSION

**Package**: slide-narrator  
**Version**: $VERSION

This is part of the unified Slide release v$VERSION. All Slide packages at version $VERSION are guaranteed compatible.

See [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/packages/narrator/CHANGELOG.md) for details." \
            packages/narrator/dist/*
          
          # Space Monkey release
          gh release create "space-monkey-v$VERSION" \
            --title "Space Monkey v$VERSION" \
            --notes "Release Space Monkey v$VERSION

**Package**: slide-space-monkey  
**Version**: $VERSION

This is part of the unified Slide release v$VERSION. All Slide packages at version $VERSION are guaranteed compatible.

See [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/packages/space-monkey/CHANGELOG.md) for details." \
            packages/space-monkey/dist/*
          
          # Lye release
          gh release create "lye-v$VERSION" \
            --title "Lye v$VERSION" \
            --notes "Release Lye v$VERSION

**Package**: slide-lye  
**Version**: $VERSION

This is part of the unified Slide release v$VERSION. All Slide packages at version $VERSION are guaranteed compatible.

See [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/packages/lye/CHANGELOG.md) for details." \
            packages/lye/dist/*
          
          echo "✓ All GitHub releases created"

