name: Release Space Monkey

on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-space-monkey:
    # Only run if PR was merged and branch matches release/space-monkey-v*
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/space-monkey-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Validate this is a space-monkey release
        run: |
          if [[ ! "${{ github.event.pull_request.head.ref }}" =~ ^release/space-monkey-v.*$ ]]; then
            echo "ERROR: This workflow should only run for space-monkey releases"
            echo "Branch: ${{ github.event.pull_request.head.ref }}"
            exit 1
          fi
          echo "✓ Confirmed this is a space-monkey release"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          uv tool install hatch
      
      - name: Extract version from PR branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/space-monkey-v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
      
      - name: Verify version matches pyproject.toml
        run: |
          cd packages/space-monkey
          PYPROJECT_VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          echo "pyproject.toml version: $PYPROJECT_VERSION"
          echo "Branch version: $VERSION"
          if [ "$PYPROJECT_VERSION" != "$VERSION" ]; then
            echo "Version mismatch! pyproject.toml has $PYPROJECT_VERSION but branch has $VERSION"
            exit 1
          fi
      
      - name: Create and push tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "space-monkey-v$VERSION" -m "Release Space Monkey version $VERSION"
          git push origin "space-monkey-v$VERSION"
      
      - name: Build Space Monkey package
        run: |
          cd packages/space-monkey
          uv tool run hatch build
      
      - name: Publish Space Monkey to PyPI
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd packages/space-monkey
          uv tool run hatch publish
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: space-monkey-v${{ env.VERSION }}
          release_name: Space Monkey v${{ env.VERSION }}
          body: |
            Release Space Monkey v${{ env.VERSION }}
            
            Package: slide-space-monkey
            Version: ${{ env.VERSION }}
            
            See the [changelog](packages/space-monkey/CHANGELOG.md) for details.
          draft: false
          prerelease: false 