name: Test Packages

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'examples/**'
      - 'tests/**'
      - '.github/workflows/test.yml'

jobs:
  test-narrator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install workspace dependencies
        run: |
          uv sync --dev
      
      - name: Run Narrator tests
        run: |
          cd packages/narrator
          uv run pytest tests/

  test-tyler:
    runs-on: ubuntu-latest
    needs: [test-narrator]
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install workspace dependencies
        run: |
          uv sync --dev
      
      - name: Run Tyler tests
        run: |
          cd packages/tyler
          uv run pytest tests/

  test-space-monkey:
    runs-on: ubuntu-latest
    needs: [test-narrator]
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install workspace dependencies
        run: |
          uv sync --dev
      
      - name: Run Space Monkey tests
        run: |
          cd packages/space-monkey
          uv run pytest tests/

  test-lye:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic1 poppler-utils
      
      - name: Install workspace dependencies
        run: |
          uv sync --dev
      
      - name: Run Lye tests
        run: |
          cd packages/lye
          uv run pytest tests/

  integration-test:
    runs-on: ubuntu-latest
    needs: [test-tyler, test-narrator, test-space-monkey, test-lye]
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic1 poppler-utils
      
      - name: Install workspace dependencies
        run: |
          uv sync --dev
      
      - name: Test Tyler imports and basic functionality
        run: |
          uv run python -c "
          import tyler
          from tyler import Agent
          print('Tyler imports successfully')
          
          # Test basic agent creation
          agent = Agent(name='test', instructions='test')
          print('Tyler Agent created successfully')
          "
      
      - name: Test Narrator imports and basic functionality
        run: |
          uv run python -c "
          import narrator
          from narrator import ThreadStore
          print('Narrator imports successfully')
          
          # Test basic thread store creation
          store = ThreadStore()
          print('Narrator ThreadStore created successfully')
          "
      
      - name: Test Space Monkey imports and basic functionality
        run: |
          uv run python -c "
          import space_monkey
          print('Space Monkey imports successfully')
          print(f'Space Monkey version: {space_monkey.__version__}')
          "
      
      - name: Test Lye imports and basic functionality
        run: |
          uv run python -c "
          import lye
          from lye import TOOLS, WEB_TOOLS, FILES_TOOLS
          print('Lye imports successfully')
          print(f'Lye version: {lye.__version__}')
          print(f'Total tools available: {len(TOOLS)}')
          "

  test-examples:
    runs-on: ubuntu-latest
    needs: [test-tyler, test-narrator, test-space-monkey, test-lye]
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic1 poppler-utils
      
      - name: Install workspace dependencies
        run: |
          uv sync --dev
      
      - name: Run example smoke tests
        run: |
          uv run python tests/run_examples.py --smoke --verbose
      
      - name: Test example imports
        run: |
          uv run pytest tests/test_examples.py::test_examples_can_be_imported -v
      
      - name: Test examples directory structure
        run: |
          uv run pytest tests/test_examples.py::test_examples_directory_structure -v 