name: Test Packages

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/**'
      - '.github/workflows/test.yml'

jobs:
  test-tyler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Tyler dependencies
        run: |
          cd packages/tyler
          uv sync --dev
      
      - name: Run Tyler tests
        run: |
          cd packages/tyler
          uv run pytest tests/

  test-narrator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Narrator dependencies
        run: |
          cd packages/narrator
          uv sync --dev
      
      - name: Run Narrator tests
        run: |
          cd packages/narrator
          uv run pytest tests/

  integration-test:
    runs-on: ubuntu-latest
    needs: [test-tyler, test-narrator]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install both packages
        run: |
          uv pip install --system -e packages/narrator
          uv pip install --system -e packages/tyler
      
      - name: Test Tyler imports and basic functionality
        run: |
          python -c "
          import tyler
          from tyler import Agent
          print('Tyler imports successfully')
          
          # Test basic agent creation
          agent = Agent(name='test', instructions='test')
          print('Tyler Agent created successfully')
          "
      
      - name: Test Narrator imports and basic functionality
        run: |
          python -c "
          import narrator
          from narrator import ThreadStore
          print('Narrator imports successfully')
          
          # Test basic thread store creation
          store = ThreadStore()
          print('Narrator ThreadStore created successfully')
          " 